### PR TITLE
 upgrade to 0.18.0 via elm-upgrade

### PR DESCRIPTION
**Pull request by robotarmy**
Hi there! I have been learning elm and wanted to use your tools in elm 0.18.0.

These are the results of running the project through elm-upgrade and elm-format-0.18.0

Thanks for your work and elm-bootstrap-html && elm-html-shorthand. Happy New Year!

### CODE REVIEW

**Comment by stkb** [comment]
Hi @robotarmy thanks for the PR. Unfortunately the library doesn't compile in this state and would need some more work. As well as some rewriting around functions that no longer exist in the core libraries, the main problem is what to do about the function names.

Most elements in Html.Shorthand have two forms, eg: `img_` and `img'`. The elm-upgrade has just renamed all the `'` functions, also to `_` (because names with `'` are no longer allowed in Elm), leaving duplicate names everywhere. A solution to this naming conflict needs to be thought-of.*

However I don't know how @rehno-lindeque feels about solving this problem and publishing a new version of this library. I myself started using it when I was new to Elm, because I thought it saved some typing an added some convenience. However I've now come back to just using the core html library, feeling the extra layer of elm-html-shorthand isn't really worth it. So I'd encourage you to try the same.

----

\* One idea might be to remove the existing shorthand (`_`) versions, since the added-value of these is less (there's not a lot of difference between typing `div_ [ children ]` and `div [] [ children ]`). This would then free the `_` suffix for the idiomatic-form functions (currently with `'` suffix).

**Comment by agrafix** [comment]
Btw: this change introduces a lot of whitespace / formatting changes that should (in my opinion) be done in another PR so it's clear what actually changed...

**Comment by rehno-lindeque** [comment]
I am happy to merge and publish an upgrade to elm-html-shorthand by the way. This package is at least reasonably complete (elm-html-bootstrap OTOH is probably missing at least 95% of bootstrap which makes me feel that introducing more people to it is doing more harm than good with all the better options out there).

(I am writing extremely little elm code at the moment, I'm sorry for being so scarce)

**Review by stkb — CHANGES_REQUESTED** [review]
Summary for review: The PR is incomplete and I'm not sure how helpful the elm-format upgrade tool has been here really.

Doesn't compile because some functions need to be rewritten in Events.Elm (use of Json.customDecoder, object2, Result.formatError etc. that are gone from the core library).

Most importantly those wishing to still use the library with 0.18 need to come up with an alternative naming scheme now that names with `'` are disallowed.

**Review by agrafix — CHANGES_REQUESTED** [review]
See above: Please don't mix so many formatting/whitespace changes with actual changes. Other than that, see @stkb 's review.

**Pull request closed without merging**
